name: hackathon_s1mple
description: Share widget
version: 1.0
homepage: https://vinbrain.net
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dotted_border: ^2.0.0
  file_picker: ^4.0.2
  flutter_rating_bar: ^4.0.0
  image_picker: ^0.8.4
  photo_view: ^0.12.0
  shimmer: ^2.0.0
  webview_flutter: ^2.0.12
  flutter_html: ^2.1.2
  video_call:
    path: ../video_call
  open_file: ^3.2.1
  overlay_support: ^1.2.1
  permission_handler: ^7.0.0
  image: ^3.0.8
  crop_image: ^1.0.1
  connectivity: ^3.0.6
  flutter_svg: ^0.22.0
  expandable_page_view: ^1.0.6
  camera: ^0.9.4+11
  google_sign_in: ^5.2.4
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.1
  flutter_facebook_auth: ^4.1.2
  phone_number: ^0.12.0
  qr_code_scanner: ^0.4.0
  sms_autofill: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  freezed: ^0.14.5
  json_annotation: ^4.1.0
  json_serializable: ^5.0.0
  pedantic: ^1.11.1
  intl_utils: ^2.4.0
  injectable_generator: ^1.5.2

dependency_overrides:
  analyzer: ^2.2.0


flutter:
  uses-material-design: true
  assets:
    - assets/